name: @project.name@
version: @project.version@
main: com.github.kory33.signvote.core.SignVote
description: A Bukkit plugin that allows player to vote through signs.

author: kory33

commands:
    signvote:
        usage: /signvote - displays the help
        description: displays the help

permissions:
    signvote.vote:
        description: allows a player to vote
        default: true
    signvote.votemore:
        description: allows a player to vote more
        default: op
    signvote.unvote:
        description: allows a player to cancel a vote
        default: true
    signvote.createsign:
        description: allows a player to create a new vote endpoint
        default: op
    signvote.createsession:
        description: allows a player to create a vote session
        default: op
    signvote.modifysession:
        description: allows a player to modify the existing session
        default: op
    signvote.listsession:
        description: allows a player to obtain the session list
        default: op
    signvote.opensession:
        description: allows a player to re-open a closed session
        default: op
    signvote.closesession:
        description: allows a player to close an opened session
        default: op
    signvote.deletesession:
        description: allows a player to delete an existing session
        default: op
    signvote.deletevotepoint:
        description: allows a player to delete a votepoint
        default: op
    signvote.reload:
        description: allows a player to reload the plugin
        default: op
    signvote.save:
        description: allows a player to save plugin data
        default: op
