name: SignVote
version: 0.1.0
main: com.github.kory33.signvote.core.SignVote
description: A Bukkit plugin that allows player to vote through signs.

author: kory33

commands:
    signvote:
        usage: /signvote - displays the help
        description: displays the help

permissions:
    signvote.vote:
        description: allows a player to vote
        default: true
    signvote.createsign:
        description: allows a player to create a new vote endpoint
        default: op
    signvote.createsession:
        description: allows a player to create a vote session
        default: op
    signvote.modifysession:
        description: allows a player to modify the existing session
        default: op
    signvote.opensession:
        description: allows a player to re-open a closed session
        default: op
    signvote.closesession:
        description: allows a player to close an opened session
        default: op
    signvote.deletevotepoint:
        description: allows a player to delete a votepoint
        default: op
